[package]
name = "maiq_parser"
authors = ["pashokitsme <pashamail79@gmail.com>"]
repository = "https://github.com/pashokitsme/maiq-parser"
license = "MPL-2.0"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true
opt-level = "s"

[lib]

[dependencies]
aho-corasick = "0.7.20"
chrono = { version = "0.4.23", features = ["serde"] }
dotenvy = "0.15.6"
env_logger = "0.10.0"
lazy_static = "1.4.0"
pretty-sha2 = "0.1.5"
regex = "1.7.0"
reqwest = { version = "0.11.13" }
serde = { version = "1.0.149", features = ["derive"] }
sha2 = "0.10.6"
stopwatch = "0.0.7"
thiserror = "1.0.37"

#todo replace with tl
scraper = "0.13.0"
table-extract = "0.2.2"