[package]
name = "maiq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
pretty-sha2 = "0.1.5"
reqwest = { version = "0.11.13", features = ["serde_json"] }
sha2 = "0.10.6"
tl = "0.7.7"
tokio = "1.23.0"
