[package]
name = "maiq_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "0.7.20"
chrono = { version = "0.4.23", features = ["serde"] }
dotenvy = "0.15.6"
env_logger = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.17"
logger = "0.4.0"
pretty-sha2 = "0.1.5"
pretty_env_logger = "0.4.0"
regex = "1.7.0"
reqwest = { version = "0.11.13", features = ["serde_json"] }
scraper = "0.13.0"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
sha2 = "0.10.6"
stopwatch = "0.0.7"
table-extract = "0.2.2"
thiserror = "1.0.37"
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }


# mio, tower, warp