[package]
name = "maiq-shared"
authors = ["pashokitsme <pashamail79@gmail.com>"]
version = "0.4.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
lazy_static = "1.4.0"
serde = "1.0.152"
sha2 = "0.10.6"
