name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cargo +stable-msvc build --profile cli --feature cli

      - name: Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          title: Latest build
          files: ./target/cli/maiq-parser.tar.gz
          prerelease: false